# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /zfs-pool/xsirov00/out/Meta-Llama-3-8B/
  checkpoint_files: [
    meta_model_1.pt,
  ]
  output_dir: /zfs-pool/xsirov00/out/Meta-Llama-3-8B/
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /zfs-pool/xsirov00/torchtune/Meta-Llama-3-8B/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "Kam pojdeme na obed metju?"
instruct_template: null
chat_format: null
max_new_tokens: 100
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

quantizer: null
